import "./globals.css";
import { Inter } from "next/font/google";
import AppProviders from "@/providers/AppProviders";
import Navbar from "@/components/shared/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={inter.className}>
				<AppProviders>
					<Navbar />
					<main className="min-h-screen">{children}</main>
				</AppProviders>
			</body>
		</html>
	);
}
